package entities;

import database.Database;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import org.apache.commons.lang3.*;

public class User implements Identifiable, Serializable {
    @Serial
    private static final long serialVersionUID = -4624705422767438747L;
    private static int idCounter;

    private final int id;
    private final String name;
    private final String surname;
    private final String username;
    private final String password;
    private final List<Booking> bookings;

    static {
        idCounter = Database.getIdCounter("User");
    }


    //constructors
    public User(String name, String surname, String username, String password) {
        this.id = idCounter++;
        this.name = name;
        this.surname = surname;
        this.username = username;
        this.password = password;
        bookings = new ArrayList<>();
    }

    //getter and setters
    public static int getIdCounter() {
        return idCounter;
    }

    @Override
    public int getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public List<Booking> getAllBookings() {
        return bookings;
    }


    //methods
    //static methods
    /*
     * returns a random User whose:
     * * name and surname is a random alphabetical String of a random length between 3 (inc.) and 10 (exc.)
     * * username is a random alphanumerical String of a random length between 3 (inc.) and 10 (exc.)
     * * password is a random String containing any character except space and control characters of a random
     *   length between 6 (inc.) and 10 (exc.)
     */
    public static User getRandom() {
        return new User(RandomStringUtils.randomAlphabetic(3, 10),
                RandomStringUtils.randomAlphabetic(3, 10),
                RandomStringUtils.randomAlphanumeric(3, 10),
                RandomStringUtils.randomGraph(6, 10));
    }

    /*
     * returns a modifiable List of random Users of specified length,
     * generated by calling User.getRandom()
     * * count - the size of the list to be returned
     */
    public static List<User> getRandom(int count) {
        return IntStream.range(0, count)
                .mapToObj(i -> getRandom())
                .collect(Collectors.toCollection(ArrayList::new));
    }

    //instance methods
    /*
     * adds the specified Booking to the bookings List.
     */
    public void addBooking(Booking booking) {
        bookings.add(booking);
    }

    /*
     * removes the specified Booking from the bookings List.
     */
    public boolean removeBooking(Booking booking) {
        return bookings.remove(booking);
    }

    /*
     * Returns true if the bookings list of this flight contains the specified Booking, otherwise false.
     */
    public boolean hasBooking(Booking booking) {
        return bookings.contains(booking);
    }

    //equals and hashcode
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return Objects.equals(username, user.username) && Objects.equals(password, user.password);
    }

    @Override
    public int hashCode() {
        return Objects.hash(username, password);
    }

    @Override
    public String toString() {
        return "User{" +
                "name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", username='" + username + '\'' +
                '}';
    }
}
